name: Validate CSV and Generate GFF

on:
  push:
    branches:
      - main
    paths:
      - 'csv/*.csv'
      - 'fasta/*.fasta'

jobs:
  validate_csv:
    if: contains(github.event.head_commit.message, '.csv')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate and Convert CSV
      run: |
        for csv_file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'csv/.*\.csv$'); do
          echo "Converting snpgene csv ${csv_file} to GFF3"
          # Check corresponding FASTA file
          base_name=$(basename "$csv_file" .csv)
          if [[ ! -f "fasta/${base_name}.fasta" ]]; then
            echo "Error: Corresponding FASTA file for $csv_file not found."
            exit 1
          fi
          # Run CSV to GFF conversion
          docker run --rm -v ${{ github.workspace }}:/workspace rocker/tidyverse:latest Rscript /workspace/scripts/make_gff_from_snap.R /workspace/$csv_file II levy_bc /workspace/gff/${base_name}.gff
        done

    - name: Commit and push GFF files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add gff/*.gff
        git commit -m "Add converted GFF file(s)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

