name: Validate GFF

on:
  push:
    branches:
      - main
    paths:
      - 'gff/*.gff'
      - 'fasta/*.fasta'
      - '.github/workflows/validate_gff.yml'

jobs:
  validate_gff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate GFF
      run: |
        for gff_file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'gff/.*\.gff$'); do
          echo "Validating GFF3 file: $gff_file"
          # Check corresponding FASTA file
          base_name=$(basename "$gff_file" .gff)
          if [[ ! -f "fasta/${base_name}.fasta" ]]; then
            echo "Error: Corresponding FASTA file for $gff_file not found."
            exit 1
          fi
          # Validate GFF file
          docker run --rm -v ${{ github.workspace }}:/workspace quay.io/biocontainers/py_fasta_validator:0.6--py38hd638cd3_4 gt gff3validator /workspace/$gff_file
        done

